# Dejar vacío deshabilita la creación del archivo PID
PidFile=
LogType=console

# Permite conexiones desde el servidor Zabbix y desde cualquier IP de la red Docker
Server=127.0.0.1,zabbix_server,172.16.0.0/12,192.168.1.0/24
ServerActive=zabbix_server

Hostname=nodo-app-zabbix
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
